  
name: ive_flutter_core_mobile
description: Core assets for InnoVet Europe Flutter projects
version: 1.2.6
homepage: https://www.harriercentral.com/
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0 
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3 

dev_dependencies:
  build_runner: ^2.4.11
  json_annotation: ^4.9.0
  freezed: ^2.5.3

dependency_overrides:
  # meta: 1.8.0


    
# name: ive_flutter_core
# description: Core assets for InnoVet Europe Flutter projects
# version: 1.2.3
# homepage: https://www.harriercentral.com/
# publish_to: none

# environment:
#   sdk: ">=2.12.0 <3.0.0"
#   flutter: ^3.7.12

# dependencies:
#   flutter:
#     sdk: flutter

#   flutter_spinkit: 5.2.0 
#   freezed_annotation: 2.4.1
#   intl: 0.18.1
#   json_annotation: 4.8.1
#   photo_view: 0.14.0 
#   qr_flutter: 4.1.0 
  
# dependency_overrides:
#   meta: 1.8.0
  
# dev_dependencies:
#   build_runner: 2.3.3
#   freezed: 2.4.5
#   json_serializable: 6.6.2


